---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: wego-system
spec:
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: hello-world
  interval: 5m0s

