---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-helm-app
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: weave-gitops-kind-kind-hello-world
  url: ssh://git@github.com/jrryjcksn/hello-world.git

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-helm-app
  namespace: wego-system
spec:
  chart:
    spec:
      chart: ./hello-world
      sourceRef:
        kind: GitRepository
        name: my-helm-app
  interval: 5m0s

